return {
  "xiyaowong/transparent.nvim",
  opts = {
    groups = { -- table: default groups
      "Normal",
      "NormalNC",
      "Comment",
      "Constant",
      "Special",
      "Identifier",
      "Statement",
      "PreProc",
      "Type",
      "Underlined",
      "Todo",
      "String",
      "Function",
      "Conditional",
      "Repeat",
      "Operator",
      "Structure",
      "LineNr",
      "NonText",
      "SignColumn",
      "CursorLineNr",
      "EndOfBuffer",
    },
    extra_groups = {
      "StatusLine",
      "StatusLineNC",
      "LineNr",
      "CursorLineFold",
      "CursorLineSign",
      "NormalFloat",
      "NvimTreeNormal",
      "NeoTreeNormalNC",
      "NeoTreeNormal",
    }, -- table: additional groups that should be cleared
    exclude_groups = {}, -- table: groups you don't want to cleared
  },
}
